
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { Suspense } from "react";

import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<div>Loading Clerk...</div>}>
        <ClerkProvider
          appearance={{
            baseTheme: undefined
          }}>
            <CartProvider>
              <WishlistProvider>
                {children}
                <Footer />
              </WishlistProvider>
            </CartProvider>
          </ClerkProvider>
        </Suspense>
      </body>
    </html>
  );
}
